<Project Sdk="Microsoft.NET.Sdk">
  
  <!-- Metadata -->
  <PropertyGroup>
    <Product>FurkanTural.Domain</Product>
    <Description>Core domain abstractions...</Description>
  </PropertyGroup>

  <!-- Assembly information -->
  <PropertyGroup>
    <AssemblyTitle>FurkanTural.Domain</AssemblyTitle>
    <AssemblyDescription>A domain library for Furkan Tural's projects.</AssemblyDescription>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>