<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- Metadata -->
  <PropertyGroup>
    <Product>FurkanTural.API</Product>
    <Description>API for Furkan Tural's projects.</Description>
  </PropertyGroup>

  <!-- Assembly information -->
  <PropertyGroup>
    <AssemblyTitle>FurkanTural.API</AssemblyTitle>
    <AssemblyDescription>API for Furkan Tural's projects.</AssemblyDescription>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <!-- Publishing settings -->
  <PropertyGroup>
    <DeleteExistingFiles>true</DeleteExistingFiles>
  </PropertyGroup>

  <!-- NuGet References -->
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
  </ItemGroup>

  <!-- Project References -->
  <ItemGroup>
    <ProjectReference Include="..\..\Business\FurkanTural_Business\FurkanTural_Business.csproj" />
    <ProjectReference Include="..\..\Signature\FurkanTural_Application\FurkanTural_Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\FurkanTural_Persistence\FurkanTural_Persistence.csproj" />
  </ItemGroup>
</Project>